### ISSUE TITLE
image vulnerabilities 

### ISSUE THREAD

**Issue by kayahk** [aws-exporters/ecr#11]
The image with version tag 0.1.4 is suffering from a lot of security issues, mainly due to the outdated Alpine base image.
Here is the report summary:
```
report:
  artifact:
    repository: aws-exporters/prometheus-ecr-exporter
    tag: 0.1.4
  registry:
    server: ghcr.io
  scanner:
    name: Trivy
    vendor: Aqua Security
    version: 0.37.2
  summary:
    criticalCount: 8
    highCount: 25
    lowCount: 0
    mediumCount: 5
    noneCount: 0
    unknownCount: 0
  updateTimestamp: "2023-02-23T16:15:20Z"
  ```
  updating the Dockerfile to use a more recent Alpine version and pushing it to our private registry for testing purposes showed that all vulnerability issues were fixed:
  ```
  report:
  artifact:
    repository: prometheus-ecr-exporter
    tag: 0.2.0
  registry:
    server: 0123456789123.dkr.ecr.eu-central-1.amazonaws.com
  scanner:
    name: Trivy
    vendor: Aqua Security
    version: 0.37.2
  summary:
    criticalCount: 0
    highCount: 0
    lowCount: 0
    mediumCount: 0
    noneCount: 0
    unknownCount: 0
  updateTimestamp: "2023-02-24T11:24:53Z"
  ```
The change on the Dockerfile I tested is this:
```
FROM alpine:3.17.2

# Installing required packages
RUN apk add --update --no-cache \
    python3~=3.10 py-pip
```
Checking Prometheus and the metrics endpoint showed no difference in functionality of the exporter service.
